version: '1.0'

services:
    web:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        ports:
            - "8006:80"
        networks:
            - database
        volumes:
            - .:/var/www/html
        env_file: .docker/env/docker.env

    mysql:
        image: mysql:8.0.35
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "33307:3306"
        networks:
            - database
        environment:
            MYSQL_DATABASE: sindicato_pjf
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: root
        volumes:
            - mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        networks:
            - database
        environment:
            PMA_HOST: mysql
            UPLOAD_LIMIT: 100M
            PMA_ABSOLUTE_URI: ""
        depends_on:
            - mysql

volumes:
    mysql:
        driver: "local"

networks:
    database:
        driver: bridge
